server:
  port: 8087
spring:
  application:
    name: container
  datasource:
    url: jdbc:mysql://localhost:3306/db_container
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

account:
  default-status: 1